-- Step 4: Daily Approved Account Engine
--
-- Creates the daily_approved_accounts table.
-- Each row is an immutable snapshot of one approved attendance_record (one team, one day).
-- Generated by the contractor via "Close Day" action.
-- On generation, the source attendance_records.frozen_at is set — blocking all further edits.
--
-- Design decisions:
--   - One row per attendance_record (not aggregated per project-day)
--   - Name fields are denormalized snapshots immune to future renames
--   - total_worker_hours = total_hours × workers_actual (worker-hours for payroll)
--   - approval_method = 'manual' | 'auto' distinguishes human vs system approval
--   - Table is insert-only by design: no UPDATE or DELETE granted to application roles

CREATE TABLE IF NOT EXISTS public.daily_approved_accounts (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at            timestamptz NOT NULL DEFAULT now(),

  -- Source linkage (1:1 with attendance_records)
  attendance_record_id  uuid NOT NULL UNIQUE REFERENCES public.attendance_records(id),

  -- Date and project identifiers
  work_date             date NOT NULL,
  project_id            uuid NOT NULL REFERENCES public.projects(id),
  contractor_id         uuid NOT NULL,
  corporation_id        uuid NOT NULL,
  team_id               uuid NOT NULL,
  team_leader_id        uuid NOT NULL,

  -- Immutable name snapshots (captured at generation time)
  project_name          text NOT NULL,
  contractor_name       text,
  corporation_name      text,
  site_manager_name     text,
  team_name             text,
  team_leader_name      text,

  -- Work data snapshot
  workers_actual        integer,
  workers_expected      integer,
  start_time            timestamptz,
  end_time              timestamptz,
  total_hours           numeric(10,4),
  total_worker_hours    numeric(10,4),
  hourly_rate           numeric(10,2),
  total_cost            numeric(10,2),

  -- Approval metadata
  approval_method       text NOT NULL DEFAULT 'manual',
  approved_at           timestamptz,
  has_exception         boolean NOT NULL DEFAULT false,
  exception_reason      text,

  -- Evidence (storage paths — sign URLs at read time)
  start_photo_url       text,
  end_photo_url         text,
  start_gps_lat         numeric,
  start_gps_lng         numeric,
  end_gps_lat           numeric,
  end_gps_lng           numeric,

  -- Generation audit
  generated_by          uuid,
  generated_at          timestamptz NOT NULL DEFAULT now()
);

-- Indexes for contractor/corporation list queries
CREATE INDEX IF NOT EXISTS daily_approved_accounts_contractor_idx
  ON public.daily_approved_accounts(contractor_id, work_date DESC);

CREATE INDEX IF NOT EXISTS daily_approved_accounts_corporation_idx
  ON public.daily_approved_accounts(corporation_id, work_date DESC);

CREATE INDEX IF NOT EXISTS daily_approved_accounts_project_date_idx
  ON public.daily_approved_accounts(project_id, work_date DESC);

-- Verification
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'daily_approved_accounts'
  ) THEN
    RAISE EXCEPTION 'Step 4 migration failed: daily_approved_accounts table not created';
  END IF;
  RAISE NOTICE 'Step 4 migration verified: daily_approved_accounts table ready.';
END $$;
