// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Hardcoded publishable fallbacks ensure the client bundle works even if
  // VITE_* env vars weren't injected at build time. These values are public
  // (anon/publishable key) — safe to ship to the browser.
  const FALLBACK_URL = "https://qzmxicshrmzehnorcgaj.supabase.co";
  const FALLBACK_KEY =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6bXhpY3Nocm16ZWhub3JjZ2FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg0NDU2ODMsImV4cCI6MjA5NDAyMTY4M30.M6MCDtuzupwtPEA8qIdNDbOzKmtdmnIHa7-ndsTAA4g";

  // process is undefined in the browser, so guard the SSR fallback.
  const serverEnv: Record<string, string | undefined> =
    typeof process !== "undefined" && process.env ? process.env : {};

  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL || serverEnv.SUPABASE_URL || FALLBACK_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    serverEnv.SUPABASE_PUBLISHABLE_KEY ||
    FALLBACK_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
